# Base configs
baseurl: "/portfolio"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Kitty Lu"
subtitle: "See the world through my eyes!"
author: "Kitty Lu"

header:
 title: "Photography"
 subtitle: "by Kitty Lu"

footer:
  name: "About Me"
  bio: "My background is in Electrical Engineering, where I previously worked as an ASIC IC Layout Engineer. I’ve loved art and drawing since I was young, and studying traditional Chinese Gongbi painting—a highly detailed brushwork style—taught me to deeply appreciate composition, color, and the subtle beauty in small details.

Over time, my creative drive expanded into photography, visual design, video production, and social media content creation. Through my involvement in community events and humanitarian relief work, I’ve developed an eye for observing subtle nuance—allowing me to capture candid moments, meaningful stories, and the unique details that give each narrative its heart."
  github: ""
  web_design: ""

social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://github.com/2KittyLu"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
