# Base configs
baseurl: "/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Kitty Lu"
subtitle: "See the world through my eyes!"
author: "Kitty Lu"
header:
 title: "Photography"
 subtitle: "by Kitty Lu"
footer:
  name: "Hi, I'm Kitty Lu"
  bio: "Bay Area photographer, videographer, and visual storyteller.
I enjoy capturing meaningful stories, genuine moments, wildlife, nature, and the beauty found in everyday life.

Through community events and humanitarian relief work, I’ve learned to look beyond the scene and capture the moments and details that tell a story."
  github: ""
  web_design: ""

social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://github.com/2KittyLu"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
