# Base configs
baseurl: "/portfolio"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Kitty Lu"
subtitle: "See the world through my eyes!"
author: "Kitty Lu"

header:
 title: "Photography"
 subtitle: "by Kitty Lu"

footer:
  name: "About Me"
  bio: "My background is in Electrical Engineering, and I previously worked as an ASIC IC Layout Engineer.

I have always loved art and drawing since I was young. I also studied traditional Chinese Gongbi painting, a detailed brush-painting style that taught me to appreciate composition, color, and the beauty of small details.

Over time, my creative interests grew into photography, visual design, video, and social media content creation. Through community events and humanitarian relief work, I’ve learned to look beyond the scene and capture genuine moments, meaningful stories, and the details that make each story unique."
  github: ""
  web_design: ""

social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://github.com/2KittyLu"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'